name: Deploy to Cloudflare Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 18013da1d185aaf02ce9e9acafbfe19e
          projectName: yagui-buscador
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
